#  Import packages

import pandas as pd

configfile: "config/config.yaml"

input_files = pd.read_table(config["input_files"]).set_index("sample", drop=False)
samples = list(input_files["sample"])

# Load rules

include: "rules/pyclone.smk"
include: "rules/filter_pyclone-vi.smk"
include: "rules/clonevol.smk"

# Target rules 

rule collect: 
    input: 
        expand("results/clonevol/{sample}.pyclone-vi.filt.clonevol.rda", sample = samples)
    output: "results/all.tsv"
    shell: "ls {input} > {output}"

rule all:
    input: "results/all.tsv"

